services:
  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'wetterstation'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'root'
    expose:
      - '3306'
    volumes:
      - db-data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    container_name: pma
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    ports:
    - 8080:80
  nodejs:
    image: node:16
    restart: always
    volumes:
      - ./:/app
    ports:
      - 3000:3000
    command: npm run dev --prefix app/
volumes:
  db-data: